[component]
array_structures = [ "content_blocks" ]
label = "Number Counter"
description = "Animated Number Counter from Zero"
icon = "plus_one"
tags = ["Text"]

[props]
alignment.select = ["left", "center", "right"]
caption_title = "This is a caption title"
main_title = "This is a main title"
description_html = "This is a description"
columns_to_display.select = ["2", "3", "4"]


[[props.items]]
alignment.select = ["left", "center", "right"]
counter_number = 0
counter_symbol = ""
title = "This is a title"
description_html = "This is a description"
