_inputs:
  date:
    instance_value: NOW
  datetime:
    instance_value: NOW

_select_data:
  columns_for_laptops:
    - 1
    - 2
    - 3
    - 4
    - 6
  columns_for_tablets:
    - 1
    - 2
    - 3
    - 4
  columns_for_mobiles:
    - 1
    - 2

  layouts:

  portfolio_layouts:
    - left-sidebar
    - right-sidebar
    - full-width

  post_layouts:
    - left-sidebar
    - right-sidebar
    - full-width

  post_categories:
    - 'Marketing'
    - 'Business'
    - 'Designs'
    - 'Relations'
    - 'Career Advice'

_collection_groups:
  - heading: Pages
    collections:
      - pages
      - portfolio
      - staff_members
  - heading: Blog
    collections:
      - posts
      - drafts
  - heading: Settings
    collections:
      - data

_structures:
  content_blocks:
    style: 'modal'

_comments:
  # Used in footer and menu yml files
  url: Enter the page url

  # Used in menu yml files
  logo_image: Use logo icon here
  logo_width: Enter logo width (default 150px)
  favicon_image: Use favicon here
  login_url: Enter login link in menu
  signup_url: Enter signup link in menu

  # Used in footer yml files
  columns_for_laptop: Default value is 3
  columns_for_tablet: Default value is 2
  columns_for_mobile: Default value is 1

  # Used in general yml files
  site_title: Enter the website title
  description: Enter the site description
  permalink: Page URL in slug format
  website_url: Enter live website domain
  font-style_url: Enter a google font url.
