[component]
array_structures = [ "content_blocks" ]
label = "Info section"
description = "Title and caption title above with icon, description and a call to action below"
icon = "view_stream"
tags = ["Text"]

[props]
caption_title = "This is a caption title"
main_title = "This is a main title"
description_html = "This is a description"
columns_to_display.select = ["2", "3", "4"]  #: Select the number of column for info section


[[props.items]]
alignment.select = ["left", "center", "right"]  #: Select the alignment for info section
image.default = ""  #: Select the info image
image_alt.default = "Icon image"  #: Provide the alternative text for the image
title = "This is a title"
description_html = "This is a description"
button_label = "Button name"
button_url = "Button url"
